### ISSUE TITLE
Crash with java 16.

### ISSUE THREAD

**Issue by K0-RR** [CaffeineMC/hydrogen-fabric#37]
Exiting with -1
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'hydrogen'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:137)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: java.lang.ExceptionInInitializerError
	at me.jellysquid.mods.hydrogen.common.jvm.ClassConstructors.initGuavaExtensions(ClassConstructors.java:24)
	at me.jellysquid.mods.hydrogen.common.jvm.ClassConstructors.init(ClassConstructors.java:15)
	at me.jellysquid.mods.hydrogen.common.HydrogenPreLaunch.onPreLaunch(HydrogenPreLaunch.java:9)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.RuntimeException: Could not expose method
	at me.jellysquid.mods.hydrogen.common.jvm.ClassDefineTool.<clinit>(ClassDefineTool.java:25)
	... 15 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @7f8633ae
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at me.jellysquid.mods.hydrogen.common.jvm.ClassDefineTool.<clinit>(ClassDefineTool.java:21)
	... 15 more
Process exited with code 255.

**Comment by DragonEggBedrockBreaking** [comment]
duplicate of #13

**Comment by K0-RR** [comment]
Ah so I'm dumb sorry.
