### ISSUE TITLE
Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'hydrogen'!

### ISSUE THREAD

**Issue by gitgunter** [CaffeineMC/hydrogen-fabric#55]
When I try to run my local Fabric Server, the console send this error:

Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:58)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:116)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:70)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68)
        ... 2 more
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'hydrogen'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:143)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
        ... 7 more
Caused by: java.lang.ExceptionInInitializerError
        at me.jellysquid.mods.hydrogen.common.jvm.ClassConstructors.initGuavaExtensions(ClassConstructors.java:24)
        at me.jellysquid.mods.hydrogen.common.jvm.ClassConstructors.init(ClassConstructors.java:15)
        at me.jellysquid.mods.hydrogen.common.HydrogenPreLaunch.onPreLaunch(HydrogenPreLaunch.java:12)
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
        ... 10 more
Caused by: java.lang.RuntimeException: Could not expose method
        at me.jellysquid.mods.hydrogen.common.jvm.ClassDefineTool.<clinit>(ClassDefineTool.java:25)
        ... 14 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5b275174
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at me.jellysquid.mods.hydrogen.common.jvm.ClassDefineTool.<clinit>(ClassDefineTool.java:21)
        ... 14 more
[latest.log](https://github.com/CaffeineMC/hydrogen-fabric/files/6941434/latest.log)

**Comment by srnyx** [comment]
I'm getting this too, what mods do you have @ohGunter?

**Comment by jellysquid3** [comment]
Hydrogen does not support Java 16 in Minecraft 1.16. Either downgrade to Java 11, or upgrade to Minecraft 1.17.
