### ISSUE TITLE
(1.17.1) Hydrogen release v0.3.1 incompatibility with FabricProxyLite-1.1.5

### ISSUE THREAD

**Issue by BlueGuitarCL** [CaffeineMC/hydrogen-fabric#58]
I was updating all mods as usual on the server and seems like last jar of fabric-api breaks hydrogen. I'll paste the error here.
```[Tue Nov 09] blue@zmc-cx31:~/fabric-seedtest $ ./start.sh
[19:29:03] [main/INFO]: Loading for game Minecraft 1.17.1
[19:29:03] [main/INFO]: [FabricLoader] Loading 59 mods:
        - autoconfig1u@3.3.1
        - fabric@0.42.1+1.17
        - fabric-api-base@0.4.0+5847535018
        - fabric-api-lookup-api-v1@1.3.1+5847535018
        - fabric-biome-api-v1@3.2.2+5847535018
        - fabric-blockrenderlayer-v1@1.1.6+5847535018
        - fabric-command-api-v1@1.1.4+5847535018
        - fabric-commands-v0@0.2.3+5847535018
        - fabric-containers-v0@0.1.13+5847535018
        - fabric-content-registries-v0@0.3.1+5847535018
        - fabric-crash-report-info-v1@0.1.6+5847535018
        - fabric-dimensions-v1@2.0.13+5847535018
        - fabric-entity-events-v1@1.3.1+5847535018
        - fabric-events-interaction-v0@0.4.11+5847535018
        - fabric-events-lifecycle-v0@0.2.2+5847535018
        - fabric-game-rule-api-v1@1.0.8+5847535018
        - fabric-item-api-v1@1.2.5+5847535018
        - fabric-item-groups-v0@0.3.1+5847535018
        - fabric-key-binding-api-v1@1.0.5+5847535018
        - fabric-keybindings-v0@0.2.3+5847535018
        - fabric-lifecycle-events-v1@1.4.5+5847535018
        - fabric-loot-tables-v1@1.0.5+5847535018
        - fabric-mining-level-api-v1@1.0.2+6d0fac4218
        - fabric-mining-levels-v0@0.1.5+6d0fac4218
        - fabric-models-v0@0.3.1+5847535018
        - fabric-networking-api-v1@1.0.14+5847535018
        - fabric-networking-blockentity-v0@0.2.12+5847535018
        - fabric-networking-v0@0.3.3+5847535018
        - fabric-object-builder-api-v1@1.10.11+6d0fac4218
        - fabric-object-builders-v0@0.7.5+6d0fac4218
        - fabric-particles-v1@0.2.5+5847535018
        - fabric-permissions-api-v0@0.1-SNAPSHOT
        - fabric-registry-sync-v0@0.7.13+5847535018
        - fabric-renderer-api-v1@0.4.5+5847535018
        - fabric-renderer-indigo@0.4.9+5847535018
        - fabric-renderer-registries-v1@3.2.6+6d0fac4218
        - fabric-rendering-data-attachment-v1@0.1.6+5847535018
        - fabric-rendering-fluids-v1@0.2.1+6d0fac4218
        - fabric-rendering-v0@1.1.7+6d0fac4218
        - fabric-rendering-v1@1.10.1+6d0fac4218
        - fabric-resource-loader-v0@0.4.9+5847535018
        - fabric-screen-api-v1@1.0.5+5847535018
        - fabric-screen-handler-api-v1@1.1.9+5847535018
        - fabric-structure-api-v1@1.1.14+5847535018
        - fabric-tag-extensions-v0@1.2.2+5847535018
        - fabric-textures-v0@1.0.7+5847535018
        - fabric-tool-attribute-api-v1@1.3.1+eb76084f18
        - fabric-transfer-api-v1@1.5.1+6d0fac4218
        - fabricloader@0.11.7
        - fabricproxy-lite@1.1.5
        - hydrogen@0.3
        - java@17
        - lithium@0.7.5
        - luckperms@5.3.74
        - minecraft@1.17.1
        - phosphor@0.7.2+build.180
        - servux@0.1.0
        - spawnprotectiontweaks@0.3+1.17.1
        - syncmatica@0.2.6
[19:29:04] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/blue/fabric-seedtest/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[19:29:04] [main/INFO]: Compatibility level set to JAVA_16
[19:29:04] [main/INFO]: Loaded configuration file for Lithium: 87 options available, 0 override(s) found
[19:29:05] [main/WARN]: @Mixin target net/minecraft/class_3218$class_5526 is public in fabric-lifecycle-events-v1.mixins.json:ServerWorldEntityLoaderMixin and should be specified in value
[19:29:05] [main/FATAL]: Mixin prepare failed preparing util.MixinIdentifier in hydrogen.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: hydrogen.mixins.json:util.MixinIdentifier target net.minecraft.class_2960 was loaded too early.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: hydrogen.mixins.json:util.MixinIdentifier target net.minecraft.class_2960 was loaded too early.
        at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:938) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:872) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:648) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106) ~[fabric-server-launch.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1219) ~[?:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:143) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:58)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:116)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:70)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68)
        ... 2 more
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'hydrogen'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:143)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
        ... 7 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [hydrogen.mixins.json:util.MixinIdentifier] from phase [DEFAULT] in config [hydrogen.mixins.json] FAILED during PREPARE
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:590)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:517)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
        at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1219)
        at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
        at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191)
        at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
        ... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: hydrogen.mixins.json:util.MixinIdentifier target net.minecraft.class_2960 was loaded too early.
        at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:938)
        at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:872)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:648)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514)
        ... 28 more
[Tue Nov 09] blue@zmc-cx31:~/fabric-seedtest $ ls ../fabric-zmc-hetzner/mods/
total 3.6M
-rw-r--r-- 1 blue blue 1.1M Oct 17 18:27 fabric-api-0.41.0+1.17.jar
-rw-r--r-- 1 blue blue 116K Jul 15 22:33 hydrogen-fabric-mc1.17.1-0.3.jar
```

**Comment by MeeniMc** [comment]
There is a newer version 0.3.1 that I am using with fabric-api-0.41.2, try upgrading. 

From the dates you may already have it (hard to tell as 0.3.1 self reports as 0.3), can you replicate with only Hydrogen? It could be a mod incompatibility.

**Comment by BlueGuitarCL** [comment]
The logs i sent at that moment were for fabric-api-0.42.1, and it worked on Hydrogen 0.3.1 and on the latest api too (api-0.42.1)
But after discarding my mod list one by one (tested with fabric-loader-0.12.5+1.17.1), the issue dissapeared when i unloaded FabricProxyLite, and both mods are crucial for the network so.. i would appreciate if both mods can work together.

Edit: Im starting to suspect why both mods worked alongside before and now with newer api and loader it doesnt work anymore. No idea what it can be
